version: '3'
services:
  dota-game-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    command: serve
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
